//! Typed emit helpers from Neutrino Spectra schemas.
//!
//! Each type below is generated by a `spectra_schema!` / `spectra_metric!` invocation in
//! `schemas/`; the `*Logger` / `*Recorder` types are what [`crate::sink_forward`] calls to
//! emit a row or bump a counter.
//!
//! # Examples
//!
//! ```rust,no_run
//! use neutrino_spectra_telemetry::helpers::NeutrinoSecretAccessRecorder;
//!
//! NeutrinoSecretAccessRecorder::record(
//!     1,
//!     serde_json::json!({"action": "read", "outcome": "granted"}),
//! );
//! ```

/// Recorder for the `neutrino_secret_access` counter.
pub use crate::schemas::neutrino_secret_access::NeutrinoSecretAccessRecorder;
/// Row type and logger for the `neutrino_secret_access_log` event table.
pub use crate::schemas::neutrino_secret_access_log::{
    NeutrinoSecretAccessLog, NeutrinoSecretAccessLogLogger,
};
